version: "3.9"
services:
    mysql:
        image: mysql
        restart: always
        platform: linux/arm64/v8
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 3306:3306
    phpadmin:
        image: phpmyadmin
        restart: always
        ports:
            - 8080:80
