version: "3.9"
services:
    database:
        image: mysql
        restart: always
        platform: linux/arm64/v8
        # command: --default-authentication-plugin=mysql_native_password
        container_name: mysqldb
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel-book-review
        ports:
            - 3306:3306
    phpadmin:
        image: phpmyadmin
        restart: always
        container_name: phpmyadmin
        environment:
            PMA_PORT: 3306
            PMA_HOST: mysqldb
        ports:
            - 8080:80
    # adminer:
    #     image: adminer
    #     restart: always
    #     container_name: myadminer
    #     ports:
    #         - 8080:8080
